In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [3]:
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"


(3,)
1 2 3


In [4]:
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

[5 2 3]


In [6]:
b = np.array([[1,2,3],
              [4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
# print(b[0, 0], b[0, 1], b[1, 0]) 
print(b[0,1])

(2, 3)
2


In [7]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
              #          [ 0.  0.]]"


[[0. 0.]
 [0. 0.]]


In [13]:
b = np.ones((1,2))    # Create an array of all ones
# print(b.shape)
print(b)              # Prints "[[ 1.  1.]]"

c = np.ones((2))
# print(c.shape)
print(c)

[[1. 1.]]
[1. 1.]


In [15]:
c = np.full((2,2), 10)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[10 10]
 [10 10]]


In [16]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]] 

[[1. 0.]
 [0. 1.]]


In [17]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
             

[[0.95366605 0.03495191]
 [0.24744432 0.56655783]]


In [30]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
# print(a.shape)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
# b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
# print(a[0, 1])   # Prints "2"
# b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
# print(a[0, 1])

b = a[1:3, 2:4]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]


In [33]:
import numpy as np

a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])
# print(a.shape)
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], 
        [1, 0, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
# print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# # When using integer array indexing, you can reuse the same
# # element from the source array:
# print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# # Equivalent to the previous integer array indexing example
# print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[2 3 5]
